// <auto-generated />
using System;
using CondoNet.Auth.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CondoNet.Auth.Infrastructure.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20260625194502_InitAuth")]
    partial class InitAuth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CondoNet.Auth.Core.Entities.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganizationId")
                        .HasMaxLength(50)
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("apiKeys", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e4e4e4e4-e4e4-e4e4-e4e4-e4e4e4e4e4e4"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Llave de desarrollo para Postman",
                            IsActive = true,
                            Key = "$2a$11$v98PIDTJnp4O33B3fkBziOubl6Lup5ccvDhuZHAziRorTxlJXikGO",
                            OrganizationId = new Guid("a1a1a1a1-a1a1-a1a1-a1a1-a1a1a1a1a1a1")
                        });
                });

            modelBuilder.Entity("CondoNet.Auth.Core.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("passwordResetTokens", (string)null);
                });

            modelBuilder.Entity("CondoNet.Auth.Core.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ParentPermissionId")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ParentPermissionId");

                    b.ToTable("permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 10000,
                            Description = "Métricas consolidadas de recaudación y ocupación",
                            DisplayOrder = 1,
                            Icon = "layout-dashboard",
                            Name = "Dashboard Global",
                            Path = "/dashboard"
                        },
                        new
                        {
                            Id = 20000,
                            Description = "Configuración física e inquilinos del ERP",
                            DisplayOrder = 2,
                            Icon = "building",
                            Name = "Estructura y Activos",
                            Path = "#"
                        },
                        new
                        {
                            Id = 20100,
                            Description = "Gestión de empresas administradoras multi-tenant",
                            DisplayOrder = 1,
                            Icon = "briefcase",
                            Name = "Organizaciones (Admin)",
                            ParentPermissionId = 20000,
                            Path = "/assets/organizations"
                        },
                        new
                        {
                            Id = 20200,
                            Description = "Onboarding y gestión de edificios/complejos",
                            DisplayOrder = 2,
                            Icon = "home",
                            Name = "Condominios",
                            ParentPermissionId = 20000,
                            Path = "/assets/condominiums"
                        },
                        new
                        {
                            Id = 20300,
                            Description = "Subdivisiones físicas de la infraestructura",
                            DisplayOrder = 3,
                            Icon = "layers",
                            Name = "Torres y Bloques",
                            ParentPermissionId = 20000,
                            Path = "/assets/towers"
                        },
                        new
                        {
                            Id = 20400,
                            Description = "Mantenimiento, áreas y alícuotas de apartamentos/locales",
                            DisplayOrder = 4,
                            Icon = "door-closed",
                            Name = "Unidades",
                            ParentPermissionId = 20000,
                            Path = "/assets/units"
                        },
                        new
                        {
                            Id = 20500,
                            Description = "Importador diferido asíncrono de infraestructura",
                            DisplayOrder = 5,
                            Icon = "file-spreadsheet",
                            Name = "Carga Masiva (Bulk)",
                            ParentPermissionId = 20000,
                            Path = "/assets/bulk-import"
                        },
                        new
                        {
                            Id = 30000,
                            Description = "Gestión del padrón de copropietarios y residentes",
                            DisplayOrder = 3,
                            Icon = "users",
                            Name = "Comunidad",
                            Path = "#"
                        },
                        new
                        {
                            Id = 30100,
                            Description = "Directorio legal de dueños de inmuebles",
                            DisplayOrder = 1,
                            Icon = "user-check",
                            Name = "Propietarios",
                            ParentPermissionId = 30000,
                            Path = "/community/owners"
                        },
                        new
                        {
                            Id = 30200,
                            Description = "Control de habitantes, cargas familiares y mascotas",
                            DisplayOrder = 2,
                            Icon = "smile",
                            Name = "Inquilinos y Residentes",
                            ParentPermissionId = 30000,
                            Path = "/community/residents"
                        },
                        new
                        {
                            Id = 30300,
                            Description = "Control de tags y patentes vehiculares permitidas",
                            DisplayOrder = 3,
                            Icon = "car",
                            Name = "Vehículos y Accesos",
                            ParentPermissionId = 30000,
                            Path = "/community/vehicles"
                        },
                        new
                        {
                            Id = 40000,
                            Description = "Explotación comercial de áreas comunes y estacionamientos",
                            DisplayOrder = 4,
                            Icon = "calendar-days",
                            Name = "Servicios y Áreas",
                            Path = "#"
                        },
                        new
                        {
                            Id = 40100,
                            Description = "Alquiler y control de puestos de parking a terceros",
                            DisplayOrder = 1,
                            Icon = "truck",
                            Name = "Estacionamientos Externos",
                            ParentPermissionId = 40000,
                            Path = "/services/parking"
                        },
                        new
                        {
                            Id = 40200,
                            Description = "Alquiler controlado de salones de fiesta, parrilleras, etc.",
                            DisplayOrder = 2,
                            Icon = "palmtree",
                            Name = "Reserva de Amenities",
                            ParentPermissionId = 40000,
                            Path = "/services/amenities"
                        },
                        new
                        {
                            Id = 50000,
                            Description = "Motor de cuentas corrientes y emisión de recibos",
                            DisplayOrder = 5,
                            Icon = "credit-card",
                            Name = "Facturación y Cobros",
                            Path = "#"
                        },
                        new
                        {
                            Id = 50100,
                            Description = "Registro de planillas de gastos del mes (Luz, Agua, etc.)",
                            DisplayOrder = 1,
                            Icon = "receipt",
                            Name = "Gastos Comunes",
                            ParentPermissionId = 50000,
                            Path = "/billing/expenses"
                        },
                        new
                        {
                            Id = 50200,
                            Description = "Procesamiento masivo de cuotas de mantenimiento",
                            DisplayOrder = 2,
                            Icon = "file-invoice-dollar",
                            Name = "Emisión de Recibos",
                            ParentPermissionId = 50000,
                            Path = "/billing/invoice-generation"
                        },
                        new
                        {
                            Id = 50300,
                            Description = "Consulta de saldos de las unidades habitacionales",
                            DisplayOrder = 3,
                            Icon = "wallet",
                            Name = "Estados de Cuenta",
                            ParentPermissionId = 50000,
                            Path = "/billing/statements"
                        },
                        new
                        {
                            Id = 50400,
                            Description = "Aprobación de transferencias reportadas por propietarios",
                            DisplayOrder = 4,
                            Icon = "check-square",
                            Name = "Validación de Pagos",
                            ParentPermissionId = 50000,
                            Path = "/billing/payments-validation"
                        },
                        new
                        {
                            Id = 60000,
                            Description = "Libro Mayor, Partida Doble y Autómatas Contables",
                            DisplayOrder = 6,
                            Icon = "landmark",
                            Name = "Contabilidad Core",
                            Path = "#"
                        },
                        new
                        {
                            Id = 60100,
                            Description = "CRUD visual y jerárquico del árbol contable",
                            DisplayOrder = 1,
                            Icon = "git-fork",
                            Name = "Plan de Cuentas",
                            ParentPermissionId = 60000,
                            Path = "/accounting/chart-of-accounts"
                        },
                        new
                        {
                            Id = 60200,
                            Description = "Registro manual, consulta y anulación quirúrgica de asientos",
                            DisplayOrder = 2,
                            Icon = "book",
                            Name = "Libro Diario",
                            ParentPermissionId = 60000,
                            Path = "/accounting/journal-entries"
                        },
                        new
                        {
                            Id = 60300,
                            Description = "Configuración de plantillas e impuestos basados en eventos",
                            DisplayOrder = 3,
                            Icon = "cpu",
                            Name = "Autómata Contable",
                            ParentPermissionId = 60000,
                            Path = "/accounting/automaton-templates"
                        },
                        new
                        {
                            Id = 60400,
                            Description = "Reporte automatizado de Activos, Pasivos y Patrimonio",
                            DisplayOrder = 4,
                            Icon = "scale",
                            Name = "Balance General",
                            ParentPermissionId = 60000,
                            Path = "/accounting/reports/balance-sheet"
                        },
                        new
                        {
                            Id = 60500,
                            Description = "Estado dinámico de Ganancias y Pérdidas del ejercicio",
                            DisplayOrder = 5,
                            Icon = "trending-up",
                            Name = "Estado de Resultados",
                            ParentPermissionId = 60000,
                            Path = "/accounting/reports/income-statement"
                        },
                        new
                        {
                            Id = 90000,
                            Description = "Seguridad informática, accesos y auditoría forense",
                            DisplayOrder = 99,
                            Icon = "sliders",
                            Name = "Configuración Sistema",
                            Path = "#"
                        },
                        new
                        {
                            Id = 90100,
                            Description = "Control de credenciales, perfiles y bloqueos",
                            DisplayOrder = 1,
                            Icon = "user-cog",
                            Name = "Gestión de Usuarios",
                            ParentPermissionId = 90000,
                            Path = "/system/users"
                        },
                        new
                        {
                            Id = 90200,
                            Description = "Definición de perfiles (Admin, Contador, Comité)",
                            DisplayOrder = 2,
                            Icon = "shield-check",
                            Name = "Roles del Sistema",
                            ParentPermissionId = 90000,
                            Path = "/system/roles"
                        },
                        new
                        {
                            Id = 90300,
                            Description = "Mapeo dinámico de accesos por rol",
                            DisplayOrder = 3,
                            Icon = "lock",
                            Name = "Matriz de Permisos",
                            ParentPermissionId = 90000,
                            Path = "/system/permissions"
                        },
                        new
                        {
                            Id = 90400,
                            Description = "Tokens de integración para pasarelas o hardware externo",
                            DisplayOrder = 4,
                            Icon = "key-round",
                            Name = "Claves de API (ApiKeys)",
                            ParentPermissionId = 90000,
                            Path = "/system/apikeys"
                        },
                        new
                        {
                            Id = 90500,
                            Description = "Trazabilidad inmutable de acciones críticas de usuarios",
                            DisplayOrder = 5,
                            Icon = "file-search",
                            Name = "Auditoría Forense",
                            ParentPermissionId = 90000,
                            Path = "/system/audit-logs"
                        });
                });

            modelBuilder.Entity("CondoNet.Auth.Core.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("refreshTokens", (string)null);
                });

            modelBuilder.Entity("CondoNet.Auth.Core.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "SUPERADMIN"
                        },
                        new
                        {
                            Id = 2,
                            Name = "ADMIN"
                        },
                        new
                        {
                            Id = 3,
                            Name = "PROPIETARIO"
                        },
                        new
                        {
                            Id = 4,
                            Name = "INQUILINO"
                        },
                        new
                        {
                            Id = 5,
                            Name = "EXTERNO"
                        },
                        new
                        {
                            Id = 6,
                            Name = "CONSERJE"
                        },
                        new
                        {
                            Id = 7,
                            Name = "JUNTA DE CONDOMINIO"
                        },
                        new
                        {
                            Id = 8,
                            Name = "PROVEEDOR"
                        },
                        new
                        {
                            Id = 9,
                            Name = "ADMINISTRADOR DE PROPIEDAD"
                        },
                        new
                        {
                            Id = 10,
                            Name = "ADMINISTRADOR DE ESTACIONAMIENTO"
                        },
                        new
                        {
                            Id = 11,
                            Name = "AUDITO"
                        });
                });

            modelBuilder.Entity("CondoNet.Auth.Core.Entities.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("rolePermissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 10000
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 20000
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 20100
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 20200
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 20300
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 20400
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 20500
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 30000
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 30100
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 30200
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 30300
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 40000
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 40100
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 40200
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 50000
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 50100
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 50200
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 50300
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 50400
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 60000
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 60100
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 60200
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 60300
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 60400
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 60500
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 90000
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 90100
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 90200
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 90300
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 90400
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 90500
                        });
                });

            modelBuilder.Entity("CondoNet.Auth.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d3d3d3d3-d3d3-d3d3-d3d3-d3d3d3d3d3d3"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@condo.net",
                            FullName = "Admin Maestro",
                            IsActive = true,
                            PasswordHash = "$2a$11$UJFPSGUU2mYbVcEDyWSPqOLRX8CM8qoWnMhKBGlX6y2xAdGy6YuLi"
                        });
                });

            modelBuilder.Entity("CondoNet.Auth.Core.Entities.UserContext", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CondoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("OrganizationId", "CondoId");

                    b.ToTable("userContexts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f1f1f1f1-f1f1-f1f1-f1f1-f1f1f1f1f1f1"),
                            CondoId = new Guid("c2c2c2c2-c2c2-c2c2-c2c2-c2c2c2c2c2c2"),
                            OrganizationId = new Guid("a1a1a1a1-a1a1-a1a1-a1a1-a1a1a1a1a1a1"),
                            Status = 1,
                            UserId = new Guid("d3d3d3d3-d3d3-d3d3-d3d3-d3d3d3d3d3d3")
                        });
                });

            modelBuilder.Entity("RoleUserContext", b =>
                {
                    b.Property<Guid>("ContextsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RolesId")
                        .HasColumnType("int");

                    b.HasKey("ContextsId", "RolesId");

                    b.HasIndex("RolesId");

                    b.ToTable("userContextRoles", (string)null);
                });

            modelBuilder.Entity("CondoNet.Auth.Core.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("CondoNet.Auth.Core.Entities.User", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CondoNet.Auth.Core.Entities.Permission", b =>
                {
                    b.HasOne("CondoNet.Auth.Core.Entities.Permission", "ParentPermission")
                        .WithMany("ChildPermissions")
                        .HasForeignKey("ParentPermissionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentPermission");
                });

            modelBuilder.Entity("CondoNet.Auth.Core.Entities.RefreshToken", b =>
                {
                    b.HasOne("CondoNet.Auth.Core.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CondoNet.Auth.Core.Entities.RolePermission", b =>
                {
                    b.HasOne("CondoNet.Auth.Core.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CondoNet.Auth.Core.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CondoNet.Auth.Core.Entities.UserContext", b =>
                {
                    b.HasOne("CondoNet.Auth.Core.Entities.User", "User")
                        .WithMany("Contexts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RoleUserContext", b =>
                {
                    b.HasOne("CondoNet.Auth.Core.Entities.UserContext", null)
                        .WithMany()
                        .HasForeignKey("ContextsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CondoNet.Auth.Core.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CondoNet.Auth.Core.Entities.Permission", b =>
                {
                    b.Navigation("ChildPermissions");

                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("CondoNet.Auth.Core.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("CondoNet.Auth.Core.Entities.User", b =>
                {
                    b.Navigation("Contexts");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
