services:
  # --- INFRAESTRUCTURA ---
  # Base de datos exclusiva para Auth
  redis:
    image: redis:7-alpine
    container_name: condonet_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  db.auth:
    image: postgres:15-alpine
    container_name: condonet.db.auth
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DB_NAME_AUTH}
    ports:
      - "5433:5432" # Puerto para auth
    volumes:
      - auth_db_data:/var/lib/postgresql/data

  # Base de datos exclusiva para Assets
  db.asset:
    image: postgres:15-alpine
    container_name: condonet.db.asset
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DB_NAME_ASSETS}
    ports:
      - "5434:5432" # Puerto para assets
    volumes:
      - asset_db_data:/var/lib/postgresql/data

  # Base de datos exclusiva para Financials
  db.financial:
    image: postgres:15-alpine
    container_name: condonet.db.financial
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DB_NAME_FINANCIAL}
    ports:
      - "5435:5432" # Puerto para financial
    volumes:
      - financial_db_data:/var/lib/postgresql/data

  # Base de datos exclusiva para Booking
  db.booking:
    image: postgres:15-alpine
    container_name: condonet.db.booking
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DB_NAME_BOOKING}
    ports:
      - "5436:5432" # Puerto para booking
    volumes:
      - booking_db_data:/var/lib/postgresql/data

  # Base de datos exclusiva para Engagement
  db.engagement:
    image: postgres:15-alpine
    container_name: condonet.db.engagement
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DB_NAME_ENGAGEMENT}
    ports:
      - "5437:5432" # Puerto para engagement
    volumes:
      - engagement_db_data:/var/lib/postgresql/data

  # Base de datos exclusiva para Accounting
  db.accounting:
    image: postgres:15-alpine
    container_name: condonet.db.accounting
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DB_NAME_ACCOUNTING}
    ports:
      - "5438:5432" # Puerto para accounting
    volumes:
      - accounting_db_data:/var/lib/postgresql/data
 
  # Base de datos exclusiva para Payment
  db.payment:
    image: postgres:15-alpine
    container_name: condonet.db.payment
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DB_NAME_PAYMENT}
    ports:
      - "5439:5432" # Puerto para payment
    volumes:
      - payment_db_data:/var/lib/postgresql/data


  # Accceso a RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: condonet_rabbitmq
    ports:
      - "5673:5672"
      - "15673:15672"
    restart: always
    environment:
      RABBITMQ_DEFAULT_VHOST: /
      RABBITMQ_DEFAULT_HOST: ${RABBITMQ_DEFAULT_HOST}
      RABBITMQ_DEFAULT_PORT: ${RABBITMQ_DEFAULT_PORT}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

  # --- MICROSERVICIOS ---
  auth-service:
    build:
      context: .
      dockerfile: src/CondoNet.Auth.Api/Dockerfile
    container_name: condonet_auth
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db.auth;Database=${DB_NAME_AUTH};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};
      - JwtSettings__Secret=${JWT_SECRET}
      - JwtSettings__Issuer=${JWT_ISSUER}
      - JwtSettings__Audience=${JWT_AUDIENCE}
      - RabbitMQ__Host=${RABBITMQ_DEFAULT_HOST}
      - RabbitMQ__Port=${RABBITMQ_DEFAULT_PORT}
      - RabbitMQ__Username=${RABBITMQ_DEFAULT_USER} # Debe coincidir arriba
      - RabbitMQ__Password=${RABBITMQ_DEFAULT_PASS}  # Debe coincidir arriba
      - ASPNETCORE_Kestrel__Endpoints__Https__Certificate__Path=/https/condonet-dev-cert.pfx
      - ASPNETCORE_Kestrel__Endpoints__Https__Certificate__Password=${CERT_PASSWORD}
    depends_on:
      - db.auth
      - rabbitmq
    ports:
      - "8180:80"
      - "8181:443"
    volumes:
      - ./logs/auth:/app/Logs
      - ${USERPROFILE}/.aspnet/https:/https:ro
    
  assets-service:
    build:
      context: .
      dockerfile: src/CondoNet.Asset.Api/Dockerfile
    container_name: condonet_assets
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db.asset;Database=${DB_NAME_ASSETS};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};
      - JwtSettings__Secret=${JWT_SECRET}
      - JwtSettings__Issuer=${JWT_ISSUER}
      - JwtSettings__Audience=${JWT_AUDIENCE}
      - RabbitMQ__Host=${RABBITMQ_DEFAULT_HOST}
      - RabbitMQ__Port=${RABBITMQ_DEFAULT_PORT}
      - RabbitMQ__Username=${RABBITMQ_DEFAULT_USER} # Debe coincidir arriba
      - RabbitMQ__Password=${RABBITMQ_DEFAULT_PASS}  # Debe coincidir arriba
      - ASPNETCORE_Kestrel__Endpoints__Https__Certificate__Path=/https/condonet-dev-cert.pfx
      - ASPNETCORE_Kestrel__Endpoints__Https__Certificate__Password=${CERT_PASSWORD}
    depends_on:
      - db.asset
      - rabbitmq
    ports:
      - "8280:80"
      - "8281:443"
    volumes:
      - ./logs/asset:/app/Logs
      - ${USERPROFILE}/.aspnet/https:/https:ro
 
  financial-service:
    build:
      context: .
      dockerfile: src/CondoNet.Financial.Api/Dockerfile
    container_name: condonet_financial
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db.financial;Database=${DB_NAME_FINANCIAL};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};
      - JwtSettings__Secret=${JWT_SECRET}
      - JwtSettings__Issuer=${JWT_ISSUER}
      - JwtSettings__Audience=${JWT_AUDIENCE}
      - RabbitMQ__Host=${RABBITMQ_DEFAULT_HOST}
      - RabbitMQ__Port=${RABBITMQ_DEFAULT_PORT}
      - RabbitMQ__Username=${RABBITMQ_DEFAULT_USER} # Debe coincidir arriba
      - RabbitMQ__Password=${RABBITMQ_DEFAULT_PASS}  # Debe coincidir arriba
      - ASPNETCORE_Kestrel__Endpoints__Https__Certificate__Path=/https/condonet-dev-cert.pfx
      - ASPNETCORE_Kestrel__Endpoints__Https__Certificate__Password=${CERT_PASSWORD}
    depends_on:
      - db.financial
      - rabbitmq
    ports:
      - "8380:80"
      - "8381:443"
    volumes:
      - ./logs/financial:/app/Logs
      - ${USERPROFILE}/.aspnet/https:/https:ro

  booking-service:
    build:
      context: .
      dockerfile: src/CondoNet.Booking.Api/Dockerfile
    container_name: condonet_booking
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db.booking;Database=${DB_NAME_BOOKING};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};
      - JwtSettings__Secret=${JWT_SECRET}
      - JwtSettings__Issuer=${JWT_ISSUER}
      - JwtSettings__Audience=${JWT_AUDIENCE}
      - RabbitMQ__Host=${RABBITMQ_DEFAULT_HOST}
      - RabbitMQ__Port=${RABBITMQ_DEFAULT_PORT}
      - RabbitMQ__Username=${RABBITMQ_DEFAULT_USER} # Debe coincidir arriba
      - RabbitMQ__Password=${RABBITMQ_DEFAULT_PASS}  # Debe coincidir arriba
      - ASPNETCORE_Kestrel__Endpoints__Https__Certificate__Path=/https/condonet-dev-cert.pfx
      - ASPNETCORE_Kestrel__Endpoints__Https__Certificate__Password=${CERT_PASSWORD}
    depends_on:
      - redis
      - db.booking
      - rabbitmq
    ports:
      - "8480:80"
      - "8481:443"
    volumes:
      - ./logs/booking:/app/Logs
      - ${USERPROFILE}/.aspnet/https:/https:ro
 
  engagement-service:
    build:
      context: .
      dockerfile: src/CondoNet.Engagement.Api/Dockerfile
    container_name: condonet_engagement
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db.engagement;Database=${DB_NAME_ENGAGEMENT};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};
      - JwtSettings__Secret=${JWT_SECRET}
      - JwtSettings__Issuer=${JWT_ISSUER}
      - JwtSettings__Audience=${JWT_AUDIENCE}
      - RabbitMQ__Host=${RABBITMQ_DEFAULT_HOST}
      - RabbitMQ__Port=${RABBITMQ_DEFAULT_PORT}
      - RabbitMQ__Username=${RABBITMQ_DEFAULT_USER} # Debe coincidir arriba
      - RabbitMQ__Password=${RABBITMQ_DEFAULT_PASS}  # Debe coincidir arriba
      - ASPNETCORE_Kestrel__Endpoints__Https__Certificate__Path=/https/condonet-dev-cert.pfx
      - ASPNETCORE_Kestrel__Endpoints__Https__Certificate__Password=${CERT_PASSWORD}
    depends_on:
      - db.engagement
      - rabbitmq
    ports:
      - "8580:80"
      - "8581:443"
    volumes:
      - ./logs/engagement:/app/Logs
      - ${USERPROFILE}/.aspnet/https:/https:ro
 
  accounting-service:
    build:
      context: .
      dockerfile: src/CondoNet.Accounting.Api/Dockerfile
    container_name: condonet_accounting
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db.accounting;Database=${DB_NAME_ACCOUNTING};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};
      - JwtSettings__Secret=${JWT_SECRET}
      - JwtSettings__Issuer=${JWT_ISSUER}
      - JwtSettings__Audience=${JWT_AUDIENCE}
      - RabbitMQ__Host=${RABBITMQ_DEFAULT_HOST}
      - RabbitMQ__Port=${RABBITMQ_DEFAULT_PORT}
      - RabbitMQ__Username=${RABBITMQ_DEFAULT_USER} # Debe coincidir arriba
      - RabbitMQ__Password=${RABBITMQ_DEFAULT_PASS}  # Debe coincidir arriba
      - ASPNETCORE_Kestrel__Endpoints__Https__Certificate__Path=/https/condonet-dev-cert.pfx
      - ASPNETCORE_Kestrel__Endpoints__Https__Certificate__Password=${CERT_PASSWORD}
    depends_on:
      - db.accounting  
      - rabbitmq
    ports:
      - "8680:80"
      - "8681:443"
    volumes:
      - ./logs/accounting:/app/Logs
      - ${USERPROFILE}/.aspnet/https:/https:ro

  gateway-service:
    build:
      context: .
      dockerfile: src/CondoNet.Gateway.Api/Dockerfile
    container_name: condonet_gateway
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - JwtSettings__Secret=${JWT_SECRET}
      - JwtSettings__Issuer=${JWT_ISSUER}
      - JwtSettings__Audience=${JWT_AUDIENCE}
      - RabbitMQ__Host=${RABBITMQ_DEFAULT_HOST}
      - RabbitMQ__Port=${RABBITMQ_DEFAULT_PORT}
      - RabbitMQ__Username=${RABBITMQ_DEFAULT_USER} # Debe coincidir arriba
      - RabbitMQ__Password=${RABBITMQ_DEFAULT_PASS}  # Debe coincidir arriba
      - ASPNETCORE_Kestrel__Endpoints__Https__Certificate__Path=/https/condonet-dev-cert.pfx
      - ASPNETCORE_Kestrel__Endpoints__Https__Certificate__Password=${CERT_PASSWORD}
    depends_on:
      - redis
      - rabbitmq
    ports:
      - "8080:80"
      - "8081:443"
    volumes:
      - ./logs/gateway:/app/Logs
      - ${USERPROFILE}/.aspnet/https:/https:ro

  payment-service:
    build:
      context: .
      dockerfile: src/CondoNet.Payment.Api/Dockerfile
    container_name: condonet_payment
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db.payment;Database=${DB_NAME_PAYMENT};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};
      - JwtSettings__Secret=${JWT_SECRET}
      - JwtSettings__Issuer=${JWT_ISSUER}
      - JwtSettings__Audience=${JWT_AUDIENCE}
      - RabbitMQ__Host=${RABBITMQ_DEFAULT_HOST}
      - RabbitMQ__Port=${RABBITMQ_DEFAULT_PORT}
      - RabbitMQ__Username=${RABBITMQ_DEFAULT_USER} # Debe coincidir arriba
      - RabbitMQ__Password=${RABBITMQ_DEFAULT_PASS}  # Debe coincidir arriba
      - ASPNETCORE_Kestrel__Endpoints__Https__Certificate__Path=/https/condonet-dev-cert.pfx
      - ASPNETCORE_Kestrel__Endpoints__Https__Certificate__Password=${CERT_PASSWORD}
    depends_on:
      - db.payment  
      - rabbitmq
    ports:
      - "8780:80"
      - "8781:443"
    volumes:
      - ./logs/payment:/app/Logs
      - ${USERPROFILE}/.aspnet/https:/https:ro

volumes:
  pgdata:
  auth_db_data:  # Asegúrate de que este nombre sea EXACTO al que pusiste en db.auth
  asset_db_data: # Y este para el de assets
  financial_db_data: # Y este para el de financials
  booking_db_data: # Y este para el de booking
  engagement_db_data: # Y este para el de engagement
  accounting_db_data: # Y este para el de accounting
  payment_db_data: # Y este para el de payment
  redis_data:
