version: '3.8'

services:
  # --- INFRAESTRUCTURA ---
  # Base de datos exclusiva para Auth
  db.auth:
    image: postgres:15-alpine
    container_name: condonet.db.auth
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DB_NAME_AUTH}
    ports:
      - "5433:5432" # Puerto diferente para evitar conflictos locales
    volumes:
      - auth_db_data:/var/lib/postgresql/data

  # Base de datos exclusiva para Assets
  db.asset:
    image: postgres:15-alpine
    container_name: condonet.db.asset
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DB_NAME_ASSETS}
    ports:
      - "5434:5432" # Otro puerto diferente
    volumes:
      - asset_db_data:/var/lib/postgresql/data

  # Accceso a RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: condonet_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

  # --- MICROSERVICIOS ---
  auth-service:
    build:
      context: .
      dockerfile: src/CondoNet.Auth.Api/Dockerfile
    container_name: condonet_auth
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=${DB_NAME_AUTH};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};
      - JwtSettings__Secret=${JWT_SECRET}
      - JwtSettings__Issuer=${JWT_ISSUER}
      - JwtSettings__Audience=${JWT_AUDIENCE}
      - RabbitMqSettings__Host=rabbitmq
      - RabbitMqSettings__Username=${RABBITMQ_DEFAULT_USER} # Debe coincidir arriba
      - RabbitMqSettings__Password=${RABBITMQ_DEFAULT_PASS}  # Debe coincidir arriba
    depends_on:
      - db
      - rabbitmq
    ports:
      - "8080:8080"

  assets-service:
    build:
      context: .
      dockerfile: src/CondoNet.Assets.Api/Dockerfile
    container_name: condonet_assets
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=${DB_NAME_ASSETS};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};
      - JwtSettings__Secret=${JWT_SECRET}
      - JwtSettings__Issuer=${JWT_ISSUER}
      - JwtSettings__Audience=${JWT_AUDIENCE}
      - RabbitMqSettings__Host=rabbitmq
      - RabbitMqSettings__Username=${RABBITMQ_DEFAULT_USER} # Debe coincidir arriba
      - RabbitMqSettings__Password=${RABBITMQ_DEFAULT_PASS}  # Debe coincidir arriba
    depends_on:
      - db
      - rabbitmq
    ports:
      - "8081:8080"

volumes:
  pgdata:
