<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-CondoNET.Financial.Worker-f9bb97c7-9fc3-4e15-b6fb-41428c7538ad</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" Version="8.2.5" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.2.5" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CondoNet.Financial.Core\CondoNet.Financial.Core.csproj" />
    <ProjectReference Include="..\CondoNet.Financial.Infrastructure\CondoNet.Financial.Infrastructure.csproj" />
    <ProjectReference Include="..\CondoNet.Shared\CondoNet.Shared.csproj" />
  </ItemGroup>
</Project>
