<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CondoNet.Financial.Core\CondoNet.Financial.Core.csproj" />
    <ProjectReference Include="..\CondoNet.BlockChain.Core\CondoNet.BlockChain.Core.csproj" />
    <ProjectReference Include="..\CondoNet.BlockChain.Infrastructure\CondoNet.BlockChain.Infrastructure.csproj" />
    <ProjectReference Include="..\CondoNet.Shared\CondoNet.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.8" />
	<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Nethereum.Autogen.ContractApi" Version="6.0.0" />
    <PackageReference Include="Nethereum.Hex" Version="6.1.0" />
    <PackageReference Include="Nethereum.RPC" Version="6.1.0" />
    <PackageReference Include="Nethereum.Web3" Version="6.1.0" />
	<PackageReference Include="Microsoft.Extensions.Options" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
	<NethereumContract Include="Blockchain/Contracts/Mensaje.abi" ContractName="Mensaje" Namespace="CondoNet.Financial.Infrastructure.Blockchain.Contracts" />
  </ItemGroup>

</Project>
