// <auto-generated />
using System;
using CondoNet.Asset.Infraestructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CondoNet.Asset.Infraestructure.Migrations
{
    [DbContext(typeof(AssetDbContext))]
    [Migration("20260422115123_InitDb")]
    partial class InitDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CondoNet.Asset.Core.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<Guid>("CondominiumId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("DefaultRentalPrice")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsRentable")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LinkedUnitId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CondominiumId");

                    b.HasIndex("LinkedUnitId");

                    b.ToTable("assets");
                });

            modelBuilder.Entity("CondoNet.Asset.Core.Entities.Condominium", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ReserveFundPercentage")
                        .HasColumnType("numeric");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("condominiums");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Address = "Av. Principal, Edificio Sol y Mar",
                            Name = "Residencias Sol y Mar",
                            OrganizationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ReserveFundPercentage = 10.00m,
                            TaxId = "J-87654321-0"
                        });
                });

            modelBuilder.Entity("CondoNet.Asset.Core.Entities.CriticalEquipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CondominiumId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("InstallationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaintenanceFrequencyDays")
                        .HasColumnType("integer");

                    b.Property<string>("ManualUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("criticalequipments");
                });

            modelBuilder.Entity("CondoNet.Asset.Core.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<int>("Plan")
                        .HasColumnType("integer");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("TaxId")
                        .IsUnique();

                    b.ToTable("organizations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            BaseCurrency = "USD",
                            ContactEmail = "admin@condonet.test",
                            CreatedAt = new DateTime(2026, 4, 22, 11, 41, 25, 511, DateTimeKind.Utc).AddTicks(4964),
                            IsActive = true,
                            Name = "Administradora Global CondoNet",
                            Plan = 0,
                            TaxId = "J-12345678-0"
                        });
                });

            modelBuilder.Entity("CondoNet.Asset.Core.Entities.Tower", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CondominiumId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CondominiumId");

                    b.ToTable("towers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CondominiumId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Torre A",
                            OrganizationId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CondominiumId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Torre B",
                            OrganizationId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("CondoNet.Asset.Core.Entities.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Alias")
                        .HasColumnType("text");

                    b.Property<decimal>("Aliquot")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<decimal?>("AreaSquareMeters")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("CondominiumId")
                        .HasColumnType("uuid");

                    b.Property<string>("Floor")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("OwnerEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TowerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CondominiumId");

                    b.HasIndex("TowerId");

                    b.ToTable("units");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Aliquot = 50.0000m,
                            Floor = "1",
                            Identifier = "A01",
                            OrganizationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            OwnerEmail = "vecino101@test.com",
                            TowerId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Aliquot = 50.0000m,
                            Floor = "1",
                            Identifier = "A02",
                            OrganizationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            OwnerEmail = "vecino102@test.com",
                            TowerId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Aliquot = 50.0000m,
                            Floor = "1",
                            Identifier = "B01",
                            OrganizationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            OwnerEmail = "vecino101@test.com",
                            TowerId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Aliquot = 50.0000m,
                            Floor = "1",
                            Identifier = "B02",
                            OrganizationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            OwnerEmail = "vecino102@test.com",
                            TowerId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Type = 1
                        });
                });

            modelBuilder.Entity("CondoNet.Asset.Core.Entities.Asset", b =>
                {
                    b.HasOne("CondoNet.Asset.Core.Entities.Condominium", "Condominium")
                        .WithMany()
                        .HasForeignKey("CondominiumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CondoNet.Asset.Core.Entities.Unit", "LinkedUnit")
                        .WithMany("LinkedAssets")
                        .HasForeignKey("LinkedUnitId");

                    b.Navigation("Condominium");

                    b.Navigation("LinkedUnit");
                });

            modelBuilder.Entity("CondoNet.Asset.Core.Entities.Condominium", b =>
                {
                    b.HasOne("CondoNet.Asset.Core.Entities.Organization", null)
                        .WithMany("Condominiums")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CondoNet.Asset.Core.Entities.Tower", b =>
                {
                    b.HasOne("CondoNet.Asset.Core.Entities.Condominium", "Condominium")
                        .WithMany()
                        .HasForeignKey("CondominiumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Condominium");
                });

            modelBuilder.Entity("CondoNet.Asset.Core.Entities.Unit", b =>
                {
                    b.HasOne("CondoNet.Asset.Core.Entities.Condominium", null)
                        .WithMany("Units")
                        .HasForeignKey("CondominiumId");

                    b.HasOne("CondoNet.Asset.Core.Entities.Tower", "Tower")
                        .WithMany("Units")
                        .HasForeignKey("TowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tower");
                });

            modelBuilder.Entity("CondoNet.Asset.Core.Entities.Condominium", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("CondoNet.Asset.Core.Entities.Organization", b =>
                {
                    b.Navigation("Condominiums");
                });

            modelBuilder.Entity("CondoNet.Asset.Core.Entities.Tower", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("CondoNet.Asset.Core.Entities.Unit", b =>
                {
                    b.Navigation("LinkedAssets");
                });
#pragma warning restore 612, 618
        }
    }
}
